config/routes.rb
Rails.application.routes.draw do
  get 'clear_business' => 'common_actions#clear_business'
  get 'find_business' => 'common_actions#find_business'
  get 'documents' => 'common_actions#documents'
  get 'declarations' => 'common_actions#declarations'
  get 'new_vehicle', to: 'vehicles#new', as: 'new_vehicle'
  post 'create_vehicle', to: 'vehicles#create'
  get '/vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get '/edit_vehicle/:id', to: 'vehicles#edit', as: 'edit_vehicle'
  patch '/update_vehicle/:id', to: 'vehicles#update', as: 'update_vehicle'
  delete '/delete_vehicle/:id', to: 'vehicles#destroy', as: 'delete_vehicle'
  get 'new_estate', to: 'estates#new', as: 'new_estate'
  post 'create_estate', to: 'estates#create', as: 'create_estate'
  get '/estate/:id', to: 'estates#show', as: 'estate'
  get '/edit_estate/:id', to: 'estates#edit', as: 'edit_estate'
  patch '/update_estate/:id', to: 'estates#update', as: 'update_estate'
  delete '/delete_estate/:id', to: 'estates#destroy', as: 'delete_estate'
  get 'index' => 'inspector_actions#index'
  get '/list/:field' => 'inspector_actions#list', as: 'list'
  get '/show_user/:id', to: 'inspector_actions#show_user', as: 'show_user'
  get '/new_notification/:id/:receiver', to: 'notifications#new', as: 'new_notification'
  post '/create_notification/:user_id/:receiver', to: 'notifications#create', as: 'create_notification'
  get '/notification/:id', to: 'notifications#show', as: 'notification'
  delete '/delete_notification/:id', to: 'notifications#destroy', as: 'delete_notification'
  get '/new_ownership/:object_type/:object_id', to: 'ownerships#new_for_vehicle_or_estate', as: 'new_ownership'
  get '/new_ownership_for_income/:object_type/:object_id', to: 'ownerships#new_for_income', as: 'new_ownership_for_income'
  post '/create_ownership/:object_type/:object_id', to: 'ownerships#create', as: 'create_ownership'
  get '/ownership/:id', to: 'ownerships#show', as: 'ownership'
  delete '/delete_ownership/:id', to: 'ownerships#destroy', as: 'delete_ownership'
  root 'main_page#home'
  get 'sessions/new'
  get 'account' => 'personal_actions#account'
  get 'become_entrepreneur' => 'personal_actions#become_entrepreneur'
  get 'create_business' => 'personal_actions#create_business'
  patch 'confirm_status' => 'personal_actions#confirm_status'
  get 'fill_balance' => 'personal_actions#fill_balance'
  patch 'update_balance' => 'personal_actions#update_balance'
  get 'send_files' => 'personal_actions#send_files'
  post 'attach_files' => 'personal_actions#attach_files'
  get 'property' => 'personal_actions#property'
  get 'pay_taxes' => 'personal_actions#pay_taxes'
  get '/signup/:field', to: 'users#new', as: 'signup'
  post '/create_user/:user_id', to: 'users#create', as: 'create_user'
  get 'show' => 'users#show'
  get 'login' => 'sessions#new'
  post '/create_session/:field', to: 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#destroy'
  get '/auth_choice/:field' => 'sessions#auth_choice', as: 'auth_choice'
  get '/edit/:id', to: 'users#edit', as: 'edit'
  patch '/update/:id', to: 'users#update', as: 'update'
  delete '/delete_user/:id', to: 'users#destroy', as: 'delete_user'

  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/estate.rb
class Estate < ApplicationRecord
  before_create :set_tax

  VALID_CADASTRAL_NUMBER_REGEX = /\A(\d{2}:){2}\d{6}:\d{2}\z/
  validates :cadastral_number, presence: { message: "Поле Кадастровый номер не может быть пустым." },
                               uniqueness: { message: "Недвижимость с таким кадастровым номером уже зарегистрирована." },
                               format: { with: VALID_CADASTRAL_NUMBER_REGEX, 
                                         message: "Кадастровый номер не соответствует шаблону: 00:00:000000:00." }
  VALID_NUMBER_REGEX = /\A[1-9]\d*\z/
  validates :square, presence: { message: "Поле Площадь не может быть пустым." },
                     format: { with: VALID_NUMBER_REGEX, 
                               message: "Поле Площадь заполнено некорректно." }
  validates :address, presence: { message: "Поле Адрес не может быть пустым." },
                      uniqueness: { message: "Недвижимость по этому адресу уже зарегистрирована." }
  validates :cost, presence: { message: "Поле Стоимость не может быть пустым." },
                   format: { with: VALID_NUMBER_REGEX, 
                             message: "Поле Стоимость заполнено некорректно." }
  VALID_TYPE_REGEX = /\A(земля)|(жилое помещение)|(нежилое помещение)\z/
  validates :estate_type, presence: { message: "Поле Тип недвижимости не может быть пустым." },
                   format: { with: VALID_TYPE_REGEX, 
                             message: "Такого типа недвижимости не существует." }

  private

    def set_tax
      temp_square = 0
      tax_base = 0
      if (self.estate_type == 'жилое помещение')
        if (self.square > 20)
          temp_square = self.square - 20
        else
          temp_square = 1
        end
        case self.cost
          when (..10_000_000)
            tax_base = self.cost * 0.001
          when (10_000_001..20_000_000)
            tax_base = self.cost * 0.0015
          when (20_000_001..50_000_000)
            tax_base = self.cost * 0.002
          when (50_000_001..300_000_000)
            tax_base = self.cost * 0.003
          when (300_000_001..)
            tax_base = self.cost * 0.02 
        end
      else
        tax_base = self.cost * 0.005
      end
      self.tax = tax_base
    end
end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  before_action :inspector_or_admin_user, only: [:new, :create, :destroy, :edit, :update]

  def new
    @estate = Estate.new
  end

  def create
    @estate = Estate.new(estate_params)
    if @estate.save
      flash[:info] = "Информация о недвижимости дрбавлена."
      redirect_to estate_path(@estate.id)
    else
      @errors = @estate.errors.map(&:message)
      render turbo_stream: turbo_stream.update('errors', partial: 'errors')
    end
  end

  def edit
    @estate = Estate.find(params[:id])
  end

  def update
    @estate = Estate.find(params[:id])
    if @estate.update(estate_params)
      flash[:success] = "Данные о недвижимости обновлены."
      redirect_to estate_path(@estate.id)
    else
      render :edit, status: :unprocessable_entity, content_type: "text/html"
    end
  end

  def destroy
    Estate.find(params[:id]).destroy
    flash[:success] = "Информация о недвижимости удалена."
    redirect_to index_path
  end

  def show
    @estate = Estate.find(params[:id])
  end

  private

    def estate_params
      params.permit(:cadastral_number, :square, :cost, :estate_type, :address)
    end

    def inspector_or_admin_user
      redirect_to(root_path) unless current_user.inspector? || current_user.admin?
    end
end

app/helpers/estates_helper.rb
module EstatesHelper
end

app/views/estates/edit.html.erb
<h1>Редактирование информации о недвижимости</h1>

<div id="errors"></div>

<%= form_with(url: "/update_estate/#{@estate.id}", method: :patch, local: true) do |form| %>
  <% if @estate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
        <% @estate.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cadastral_number, "Кадастровый номер", style: "display: block" %>
    <%= form.text_field :cadastral_number, value: @estate.cadastral_number %>
  </div>

  <div>
    <%= form.label :square, "Площадь", style: "display: block" %>
    <%= form.text_field :square, value: @estate.square %>
  </div>

  <div>
    <%= form.label :address, "Адрес", style: "display: block" %>
    <%= form.text_field :address, value: @estate.address %>
  </div>

  <div>
    <%= form.label :cost, "Стоимость", style: "display: block" %>
    <%= form.text_field :cost, value: @estate.cost %>
  </div>

  <div>
    <%= form.label :estate_type, "Тип недвижимости", style: "display: block" %>
    <%= form.text_field :estate_type, value: @estate.estate_type %>
    <p>Допустимые типы недвижимости: земля, жилое помещение, нежилое помещение.</p>
  </div>

  <div>
    <%= form.submit "Продолжить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/estates/new.html.erb
<h1>Регистрация недвижимости</h1>

<div id="errors"></div>

<%= form_with(url: create_estate_path, method: :post, local: true) do |form| %>
  <% if @estate.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@estate.errors.count, "error") %> prohibited this estate from being saved:</h2>

      <ul>
        <% @estate.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cadastral_number, "Кадастровый номер", style: "display: block" %>
    <%= form.text_field :cadastral_number %>
  </div>

  <div>
    <%= form.label :square, "Площадь", style: "display: block" %>
    <%= form.text_field :square %>
  </div>

  <div>
    <%= form.label :address, "Адрес", style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :cost, "Стоимость", style: "display: block" %>
    <%= form.text_field :cost %>
  </div>

  <div>
    <%= form.label :estate_type, "Тип недвижимости", style: "display: block" %>
    <%= form.text_field :estate_type %>
    <p>Допустимые типы недвижимости: земля, жилое помещение, нежилое помещение.</p>
  </div>

  <div>
    <%= form.submit "Продолжить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/estates/show.html.erb
<h1><%= @estate.cadastral_number %></h1>
<h1><%= @estate.address %></h1>
<h1><%= @estate.tax %></h1>

<p><%= link_to "Редактировать", edit_estate_path(@estate.id) %></p>
<p><%= link_to "Добавить период владения", new_ownership_path("estate", @estate.id) %></p>

<% if current_user.admin? %>
  <%= button_to "Удалить недвижимость", delete_estate_path(@estate.id), method: :delete %>
<% end %>