config/routes.rb
Rails.application.routes.draw do
  get 'clear_business' => 'common_actions#clear_business'
  get 'find_business' => 'common_actions#find_business'
  get 'documents' => 'common_actions#documents'
  get 'declarations' => 'common_actions#declarations'
  get 'new_vehicle', to: 'vehicles#new', as: 'new_vehicle'
  post 'create_vehicle', to: 'vehicles#create'
  get '/vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get '/edit_vehicle/:id', to: 'vehicles#edit', as: 'edit_vehicle'
  patch '/update_vehicle/:id', to: 'vehicles#update', as: 'update_vehicle'
  delete '/delete_vehicle/:id', to: 'vehicles#destroy', as: 'delete_vehicle'
  get 'new_estate', to: 'estates#new', as: 'new_estate'
  post 'create_estate', to: 'estates#create', as: 'create_estate'
  get '/estate/:id', to: 'estates#show', as: 'estate'
  get '/edit_estate/:id', to: 'estates#edit', as: 'edit_estate'
  patch '/update_estate/:id', to: 'estates#update', as: 'update_estate'
  delete '/delete_estate/:id', to: 'estates#destroy', as: 'delete_estate'
  get 'index' => 'inspector_actions#index'
  get '/list/:field' => 'inspector_actions#list', as: 'list'
  get '/show_user/:id', to: 'inspector_actions#show_user', as: 'show_user'
  get '/new_notification/:id/:receiver', to: 'notifications#new', as: 'new_notification'
  post '/create_notification/:user_id/:receiver', to: 'notifications#create', as: 'create_notification'
  get '/notification/:id', to: 'notifications#show', as: 'notification'
  delete '/delete_notification/:id', to: 'notifications#destroy', as: 'delete_notification'
  get '/new_ownership/:object_type/:object_id', to: 'ownerships#new_for_vehicle_or_estate', as: 'new_ownership'
  get '/new_ownership_for_income/:object_type/:object_id', to: 'ownerships#new_for_income', as: 'new_ownership_for_income'
  post '/create_ownership/:object_type/:object_id', to: 'ownerships#create', as: 'create_ownership'
  get '/ownership/:id', to: 'ownerships#show', as: 'ownership'
  delete '/delete_ownership/:id', to: 'ownerships#destroy', as: 'delete_ownership'
  root 'main_page#home'
  get 'sessions/new'
  get 'account' => 'personal_actions#account'
  get 'become_entrepreneur' => 'personal_actions#become_entrepreneur'
  get 'create_business' => 'personal_actions#create_business'
  patch 'confirm_status' => 'personal_actions#confirm_status'
  get 'fill_balance' => 'personal_actions#fill_balance'
  patch 'update_balance' => 'personal_actions#update_balance'
  get 'send_files' => 'personal_actions#send_files'
  post 'attach_files' => 'personal_actions#attach_files'
  get 'property' => 'personal_actions#property'
  get 'pay_taxes' => 'personal_actions#pay_taxes'
  get '/signup/:field', to: 'users#new', as: 'signup'
  post '/create_user/:user_id', to: 'users#create', as: 'create_user'
  get 'show' => 'users#show'
  get 'login' => 'sessions#new'
  post '/create_session/:field', to: 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#destroy'
  get '/auth_choice/:field' => 'sessions#auth_choice', as: 'auth_choice'
  get '/edit/:id', to: 'users#edit', as: 'edit'
  patch '/update/:id', to: 'users#update', as: 'update'
  delete '/delete_user/:id', to: 'users#destroy', as: 'delete_user'

  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  before_create :set_tax

  VALID_VIN_REGEX = /\A[1-9]\d{16}\z/
  validates :vin, presence: { message: "Поле Уникальный идентификатор транспортного соедства не может быть пустым." },
                  uniqueness: { message: "Это транспортное средство уже зарегистрировано." },
                  format: { with: VALID_VIN_REGEX, message: "Поле Уникальный идентификатор транспортного соедства заполнено некорректно." }
  VALID_STATE_NUMBER_REGEX = /\A[авенкморстух]\d{3}[авенкморстух]{2}(\d{2}|\d{3})\z/
  validates :state_number, presence: { message: "Поле Государственный регистрационный номер не может быть пустым." },
                           uniqueness: { message: "Транспортное средство с таким номерным знаком уже зарегистрировано." },
                           format: { with: VALID_STATE_NUMBER_REGEX, 
                                     message: "Номерной знак должен быть написан кириллицей и соответствовать шаблону: а000аа00." }
  validates :model, presence: { message: "Поле Модель транспортного средства не может быть пустым." }
  VALID_POWER_REGEX = /\A[1-9]\d*\z/
  validates :power, presence: { message: "Поле Мощность не может быть пустым." },
                    format: { with: VALID_POWER_REGEX, message: "Поле Мощность заполнено некорректно." }
  VALID_VEHICLE_TYPE_REGEX = /\A(мотоцикл)|(квадрицикл)|(легковой автомобиль)|(автобус)|(грузовой автомобиль)\z/
  validates :vehicle_type, presence: { message: "Поле Тип транспортного средсва не может быть пустым." },
                           format: { with: VALID_VEHICLE_TYPE_REGEX,
                                     message: "Такого типа транспортного средства не существует." }

  private

    def set_tax
      tax_base = 0
      case vehicle_type
        when 'мотоцикл'
          case power
            when (..19) then tax_base = 7
            when (20..35) then tax_base = 15
            when (36..) then tax_base = 50
          end
        when 'квадрицикл'
          case power
            when (..50) then tax_base = 25
            when (51..) then tax_base = 50 
          end
        when 'легковой автомобиль'
          case power
            when (..100) then tax_base = 12
            when (101..125) then tax_base = 25
            when (126..150) then tax_base = 35
            when (151..175) then tax_base = 45
            when (176..200) then tax_base = 50
            when (201..225) then tax_base = 65
            when (226..250) then tax_base = 75
            when (251..) then tax_base = 150
          end
        when 'автобус'
          case power
            when (..110) then tax_base = 15
            when (111..200) then tax_base = 26
            when (201..) then tax_base = 55
          end
        when 'грузовой автомобиль'
          case power
            when (..100) then tax_base = 15
            when (101..150) then tax_base = 26
            when (151..200) then tax_base = 38
            when (201..250) then tax_base = 55
            when (251..) then tax_base = 70
          end
      end
      self.tax = power * tax_base
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :inspector_or_admin_user, only: [:new, :create, :destroy, :edit, :update]

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      flash[:info] = "Информация о транспортном средстве дрбавлена."
      redirect_to vehicle_path(@vehicle.id)
    else
      @errors = @vehicle.errors.map(&:message)
      render turbo_stream: turbo_stream.update('errors', partial: 'errors')
    end
  end

  def destroy
    Vehicle.find(params[:id]).destroy
    flash[:success] = "Информация о транспортном средстве удалена."
    redirect_to index_path
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update(vehicle_params)
      flash[:success] = "Данные о транспортном средстве обновлены."
      redirect_to vehicle_path(@vehicle.id)
    else
      render :edit, status: :unprocessable_entity, content_type: "text/html"
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
  end

  private

    def vehicle_params
      params.permit(:vin, :state_number, :model, :power, :vehicle_type)
    end

    def inspector_or_admin_user
      redirect_to(root_path) unless current_user.inspector? || current_user.admin?
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/edit.html.erb
<h1>Редактирование информации о транспортном средстве</h1>

<div id="errors"></div>

<%= form_with(url: "/update_vehicle/#{@vehicle.id}", method: :patch, local: true) do |form| %>
  <% if @vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% @vehicle.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vin, "Уникальный идентификатор транспортного средства", style: "display: block" %>
    <%= form.text_field :vin, value: @vehicle.vin %>
  </div>

  <div>
    <%= form.label :state_number, "Государственный регистрационный номер", style: "display: block" %>
    <%= form.text_field :state_number, value: @vehicle.state_number %>
    <p>Формат: а000аа00 или а000аа000.</p>
    <p>Номерной знак должен быть написан кириллицей.</p>
  </div>

  <div>
    <%= form.label :model, "Модель транспортного средства", style: "display: block" %>
    <%= form.text_field :model, value: @vehicle.model %>
  </div>

  <div>
    <%= form.label :power, "Мощность транспортного рсредства (л.с.)", style: "display: block" %>
    <%= form.text_field :power, value: @vehicle.power %>
  </div>

  <div>
    <%= form.label :vehicle_type, "Тип транспортного средства", style: "display: block" %>
    <%= form.text_field :vehicle_type, value: @vehicle.vehicle_type %>
    <p>Допустимые типы транспортных средств: мотоцикл, квадрицикл, легковой автомобиль, автобус, грузовой автомобиль.</p>
  </div>
  
  <div>
    <%= form.submit "Продолжить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/vehicles/new.html.erb
<h1>Регистрация транспортного средства</h1>

<div id="errors"></div>

<%= form_with(url: create_vehicle_path, method: :post, local: true) do |form| %>
  <% if @vehicle.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
        <% @vehicle.errors.each do |error| %>
          <li><%= error.message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vin, "Уникальный идентификатор транспортного средства", style: "display: block" %>
    <%= form.text_field :vin %>
  </div>

  <div>
    <%= form.label :state_number, "Государственный регистрационный номер", style: "display: block" %>
    <%= form.text_field :state_number %>
    <p>Формат: а000аа00 или а000аа000.</p>
    <p>Номерной знак должен быть написан кириллицей.</p>
  </div>

  <div>
    <%= form.label :model, "Модель транспортного средства", style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :power, "Мощность транспортного рсредства (л.с.)", style: "display: block" %>
    <%= form.text_field :power %>
  </div>

  <div>
    <%= form.label :vehicle_type, "Тип транспортного средства", style: "display: block" %>
    <%= form.text_field :vehicle_type %>
    <p>Допустимые типы транспортных средств: мотоцикл, квадрицикл, легковой автомобиль, автобус, грузовой автомобиль.</p>
  </div>

  <div>
    <%= form.submit "Продолжить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/vehicles/show.html.erb
<h1><%= @vehicle.state_number %></h1>
<h1><%= @vehicle.model %></h1>
<h1><%= @vehicle.tax %></h1>

<p><%= link_to "Редактировать", edit_vehicle_path(@vehicle.id) %></p>
<p><%= link_to "Добавить период владения", new_ownership_path("vehicle", @vehicle.id) %></p>

<% if current_user.admin? %>
  <%= button_to "Удалить транспортное средство", delete_vehicle_path(@vehicle.id), method: :delete %>
<% end %>