config/routes.rb
Rails.application.routes.draw do
  get 'clear_business' => 'common_actions#clear_business'
  get 'find_business' => 'common_actions#find_business'
  get 'documents' => 'common_actions#documents'
  get 'declarations' => 'common_actions#declarations'
  get 'new_vehicle', to: 'vehicles#new', as: 'new_vehicle'
  post 'create_vehicle', to: 'vehicles#create'
  get '/vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get '/edit_vehicle/:id', to: 'vehicles#edit', as: 'edit_vehicle'
  patch '/update_vehicle/:id', to: 'vehicles#update', as: 'update_vehicle'
  delete '/delete_vehicle/:id', to: 'vehicles#destroy', as: 'delete_vehicle'
  get 'new_estate', to: 'estates#new', as: 'new_estate'
  post 'create_estate', to: 'estates#create', as: 'create_estate'
  get '/estate/:id', to: 'estates#show', as: 'estate'
  get '/edit_estate/:id', to: 'estates#edit', as: 'edit_estate'
  patch '/update_estate/:id', to: 'estates#update', as: 'update_estate'
  delete '/delete_estate/:id', to: 'estates#destroy', as: 'delete_estate'
  get 'index' => 'inspector_actions#index'
  get '/list/:field' => 'inspector_actions#list', as: 'list'
  get '/show_user/:id', to: 'inspector_actions#show_user', as: 'show_user'
  get '/new_notification/:id/:receiver', to: 'notifications#new', as: 'new_notification'
  post '/create_notification/:user_id/:receiver', to: 'notifications#create', as: 'create_notification'
  get '/notification/:id', to: 'notifications#show', as: 'notification'
  delete '/delete_notification/:id', to: 'notifications#destroy', as: 'delete_notification'
  get '/new_ownership/:object_type/:object_id', to: 'ownerships#new_for_vehicle_or_estate', as: 'new_ownership'
  get '/new_ownership_for_income/:object_type/:object_id', to: 'ownerships#new_for_income', as: 'new_ownership_for_income'
  post '/create_ownership/:object_type/:object_id', to: 'ownerships#create', as: 'create_ownership'
  get '/ownership/:id', to: 'ownerships#show', as: 'ownership'
  delete '/delete_ownership/:id', to: 'ownerships#destroy', as: 'delete_ownership'
  root 'main_page#home'
  get 'sessions/new'
  get 'account' => 'personal_actions#account'
  get 'become_entrepreneur' => 'personal_actions#become_entrepreneur'
  get 'create_business' => 'personal_actions#create_business'
  patch 'confirm_status' => 'personal_actions#confirm_status'
  get 'fill_balance' => 'personal_actions#fill_balance'
  patch 'update_balance' => 'personal_actions#update_balance'
  get 'send_files' => 'personal_actions#send_files'
  post 'attach_files' => 'personal_actions#attach_files'
  get 'property' => 'personal_actions#property'
  get 'pay_taxes' => 'personal_actions#pay_taxes'
  get '/signup/:field', to: 'users#new', as: 'signup'
  post '/create_user/:user_id', to: 'users#create', as: 'create_user'
  get 'show' => 'users#show'
  get 'login' => 'sessions#new'
  post '/create_session/:field', to: 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#destroy'
  get '/auth_choice/:field' => 'sessions#auth_choice', as: 'auth_choice'
  get '/edit/:id', to: 'users#edit', as: 'edit'
  patch '/update/:id', to: 'users#update', as: 'update'
  delete '/delete_user/:id', to: 'users#destroy', as: 'delete_user'

  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/inspector_actions_controller.rb
class InspectorActionsController < ApplicationController
  before_action :inspector_or_admin_user, only: [:index, :show_user, :edit_user, :update_user]

  def index
    @users = User.order(:surname).page params[:page]
    @user = current_user
  end

  def list
    @user = current_user
    case params[:field]
      when 'users'
        @users = User.order(:surname).page params[:page]
        render turbo_stream: turbo_stream.update('index', partial: 'users')
      when 'estates'
        @estates = Estate.order(:cadastral_number).page params[:page]
        render turbo_stream: turbo_stream.update('index', partial: 'estates')
      when 'vehicles'
        @vehicles = Vehicle.order(:model).page params[:page]
        render turbo_stream: turbo_stream.update('index', partial: 'vehicles')
    end
  end

  def show_user
    @inspector = current_user
    @user = User.find(params[:id])
    unless @user.user_id == nil
      @owner = User.find(@user.user_id)
    end
    @estates = Estate.where(user_id: @user.id)
    @vehicles = Vehicle.where(user_id: @user.id)
    @notifications = Notification.where(receiver: @user.id)
    @organizations = User.where(user_id: @user.id)

  end

  def edit_user
    @user = User.find(params[:id])
  end

  def update_user
    @user = User.find(params[:id])
    if @user.update_column(:income, params[:income])
      flash[:success] = "Данные профиля обновлены."
      redirect_to show_user_path(@user.id)
    else
      @errors = @user.errors.map(&:message)
      render turbo_stream: turbo_stream.update('errors', partial: 'errors')    
    end
  end

  private

    def inspector_or_admin_user
      redirect_to(root_path) unless current_user.inspector? || current_user.admin?
    end

    def user_params_for_edit
      params.require(:user).permit(:income)
    end
end

app/helpers/inspector_actions_helper.rb
module InspectorActionsHelper
end

app/views/inspector_actions/_estates.html.erb
<p><%= link_to "Добавить новую недвижимость", new_estate_path %></p>

<%= paginate @estates %>

<div>
  <% @estates.each do |estate| %>
    <div>
      <p>
        <%= link_to estate.address, estate_path(estate.id) %>
      </p>
      <p>
        <%= estate.cadastral_number %>
      </p>
    </div>
  <% end %>
</div>

<%= paginate @estates %>

app/views/inspector_actions/_users.html.erb
<%= paginate @users %>

<div>
  <% @users.each do |user| %>
    <div>
      <p>
        <%= link_to user.full_name, show_user_path(user.id) %>
      </p>
      <p>
        <%= user.inn %>
      </p>
    </div>
  <% end %>
</div>

<%= paginate @users %>

app/views/inspector_actions/_vehicles.html.erb
<p><%= link_to "Добавить новое транспортное средство", new_vehicle_path %></p>

<%= paginate @vehicles %>

<div>
  <% @vehicles.each do |vehicle| %>
    <div>
      <p>
        <%= link_to vehicle.state_number, vehicle_path(vehicle.id) %>
      </p>
      <p>
        <%= vehicle.model %>
      </p>
    </div>
  <% end %>
</div>

<%= paginate @vehicles %>

app/views/inspector_actions/index.html.erb
<%= link_to "Пользователи", list_path('users') %>
<%= link_to "Недвижимость", list_path('estates') %>
<%= link_to "Транспортные средства", list_path('vehicles') %>

<div id="index">
  <%= render partial: 'users' %>
</div>

app/views/inspector_actions/show_user.html.erb
<h2><%= @user.full_name %></h2>
<h3>ИНН: <%= @user.inn %></h3>
<% unless @user.user_id == nil %>
  <p>Руководитель: <%= link_to @owner.full_name, show_user_path(@owner.id) %></p>
<% end %>
<p><%= link_to "Редактировать", edit_path(@user.id) %></p>
<p><%= link_to "Добавить доход", new_ownership_for_income_path('income', @user.id) %></p>
<p><%= link_to "Отправить уведомление", new_notification_path(@inspector.id, @user.id) %></p>

<% if current_user.admin? %>
  <%= button_to "Удалить пользователя", delete_user_path(@user.id), method: :delete %>
<% end %>
<% unless @organizations == nil %>
  <p>
    <% @organizations.each do |organization| %>
      <%= link_to "#{organization.full_name}", show_user_path(organization.id) %>
    <% end %>
  </p>
<% end %>
<p>
  <% @notifications.each do |notification| %>
    <%= notification.created_at %>
    <%= link_to "#{notification.preview}", notification_path(notification.id) %>
  <% end %>
</p>