config/routes.rb
Rails.application.routes.draw do
  get 'clear_business' => 'common_actions#clear_business'
  get 'find_business' => 'common_actions#find_business'
  get 'documents' => 'common_actions#documents'
  get 'declarations' => 'common_actions#declarations'
  get 'new_vehicle', to: 'vehicles#new', as: 'new_vehicle'
  post 'create_vehicle', to: 'vehicles#create'
  get '/vehicle/:id', to: 'vehicles#show', as: 'vehicle'
  get '/edit_vehicle/:id', to: 'vehicles#edit', as: 'edit_vehicle'
  patch '/update_vehicle/:id', to: 'vehicles#update', as: 'update_vehicle'
  delete '/delete_vehicle/:id', to: 'vehicles#destroy', as: 'delete_vehicle'
  get 'new_estate', to: 'estates#new', as: 'new_estate'
  post 'create_estate', to: 'estates#create', as: 'create_estate'
  get '/estate/:id', to: 'estates#show', as: 'estate'
  get '/edit_estate/:id', to: 'estates#edit', as: 'edit_estate'
  patch '/update_estate/:id', to: 'estates#update', as: 'update_estate'
  delete '/delete_estate/:id', to: 'estates#destroy', as: 'delete_estate'
  get 'index' => 'inspector_actions#index'
  get '/list/:field' => 'inspector_actions#list', as: 'list'
  get '/show_user/:id', to: 'inspector_actions#show_user', as: 'show_user'
  get '/new_notification/:id/:receiver', to: 'notifications#new', as: 'new_notification'
  post '/create_notification/:user_id/:receiver', to: 'notifications#create', as: 'create_notification'
  get '/notification/:id', to: 'notifications#show', as: 'notification'
  delete '/delete_notification/:id', to: 'notifications#destroy', as: 'delete_notification'
  get '/new_ownership/:object_type/:object_id', to: 'ownerships#new_for_vehicle_or_estate', as: 'new_ownership'
  get '/new_ownership_for_income/:object_type/:object_id', to: 'ownerships#new_for_income', as: 'new_ownership_for_income'
  post '/create_ownership/:object_type/:object_id', to: 'ownerships#create', as: 'create_ownership'
  get '/ownership/:id', to: 'ownerships#show', as: 'ownership'
  delete '/delete_ownership/:id', to: 'ownerships#destroy', as: 'delete_ownership'
  root 'main_page#home'
  get 'sessions/new'
  get 'account' => 'personal_actions#account'
  get 'become_entrepreneur' => 'personal_actions#become_entrepreneur'
  get 'create_business' => 'personal_actions#create_business'
  patch 'confirm_status' => 'personal_actions#confirm_status'
  get 'fill_balance' => 'personal_actions#fill_balance'
  patch 'update_balance' => 'personal_actions#update_balance'
  get 'send_files' => 'personal_actions#send_files'
  post 'attach_files' => 'personal_actions#attach_files'
  get 'property' => 'personal_actions#property'
  get 'pay_taxes' => 'personal_actions#pay_taxes'
  get '/signup/:field', to: 'users#new', as: 'signup'
  post '/create_user/:user_id', to: 'users#create', as: 'create_user'
  get 'show' => 'users#show'
  get 'login' => 'sessions#new'
  post '/create_session/:field', to: 'sessions#create', as: 'create_session'
  delete 'logout' => 'sessions#destroy'
  get '/auth_choice/:field' => 'sessions#auth_choice', as: 'auth_choice'
  get '/edit/:id', to: 'users#edit', as: 'edit'
  patch '/update/:id', to: 'users#update', as: 'update'
  delete '/delete_user/:id', to: 'users#destroy', as: 'delete_user'

  resources :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/personal_actions_controller.rb
class PersonalActionsController < ApplicationController
  before_action :logged_in_user, only: [:account, :become_entrepreneur, :confirm_status, :property]
  before_action :physical_user, only: [:become_entrepreneur, :create_business]

  def account
    @user = current_user
    @files = @user.files
  end

  def become_entrepreneur
    @user = current_user
  end

  def create_business
    @user = current_user
  end

  def confirm_status
    @user = current_user
    if @user.ipid == nil
      @user.generate_ipid
      flash[:success] = "Вы зарегистрированы как индивидуальный предприниматель."
      redirect_to account_path
    end
  end

  def fill_balance
    @user = current_user
  end

  def update_balance
    @user = current_user
    if @user.update(permitted_params)
      flash[:success] = "Баланс пополнен."
      redirect_to account_path
    else
      render :edit, status: :unprocessable_entity, content_type: "text/html"
    end
  end

  def property
    @user = current_user
    @ownerships = Ownership.where(user_id: @user.id)
    @current_ownerships = @ownerships.select { |object| object.end_date >= Date.parse("#{Time.now.year-1}-12-31") }
    @ownerships -= @current_ownerships
    @vehicles = @ownerships.map { |object| Vehicle.find(object.vehicle_id) unless object.vehicle_id.nil? }.uniq.compact
    @estates = @ownerships.map { |object| Estate.find(object.estate_id) unless object.estate_id.nil? }.uniq.compact
    @current_vehicles = @current_ownerships.map { |object| Vehicle.find(object.vehicle_id) unless object.vehicle_id.nil? }.uniq.compact
    @current_estates = @current_ownerships.map { |object| Estate.find(object.estate_id) unless object.estate_id.nil? }.uniq.compact
    @vehicles -= @current_vehicles
    @estates -= @current_estates
  end

  def pay_taxes
    @user = current_user
    @vehicle_ownerships = Ownership.where(user_id: @user.id, estate_id: nil)
    @estate_ownerships = Ownership.where(user_id: @user.id, vehicle_id: nil)
    @unpaid_vehicles = @vehicle_ownerships.select { |object| !object.paid? }
    @paid_vehicles = @vehicle_ownerships.select { |object| object.paid? }
    @unpaid_estates = @estate_ownerships.select { |object| !object.paid? }
    @paid_estates = @estate_ownerships.select { |object| object.paid? }
  end

  def send_files
  end

  def attach_files
    @user = current_user
    @user.files.attach(params[:files])
    flash[:info] = "Файлы загружены."
    redirect_to account_path
  end

  private

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Пожалуйста, авторизуйтесь."
        redirect_to login_path
      end
    end

    def physical_user
      if current_user.organization?
        redirect_to account_path
      end
    end

    def permitted_params
      params.permit(:balance)
    end
end

app/helpers/personal_actions_helper.rb
module PersonalActionsHelper
end

app/views/personal_actions/_ownerships.html.erb
<p></p>
<% if @paid_vehicles.empty? %>
  <% @paid_vehicles.each do |ownership| %>
    
    <%= ownership.reg_date %>
    <%= ownership.end_date %>
  <% end %>
<% end %>

<p></p>
<% if @paid_estates.empty? %>
  <% @paid_vehicles.each do |ownership| %>
    
    <%= ownership.reg_date %>
    <%= ownership.end_date %>
  <% end %>
<% end %>

<p></p>
<% if @paid_vehicles.empty? %>
  <% @paid_vehicles.each do |ownership| %>
    
    <%= ownership.reg_date %>
    <%= ownership.end_date %>
  <% end %>
<% end %>

<p></p>
<% if @paid_vehicles.empty? %>
  <% @paid_vehicles.each do |ownership| %>
    
    <%= ownership.reg_date %>
    <%= ownership.end_date %>
  <% end %>
<% end %>

app/views/personal_actions/account.html.erb
<%= @user.full_name %>
<%= @user.inn %>
<p><%= link_to "Уплата налогов", pay_taxes_path %></p>
<p><%= link_to "Пополнение баланса", fill_balance_path %></p>
<p><%= link_to "Наличие задолженности/переплаты", become_entrepreneur_path %></p>
<p><%= link_to "Подать декларацию", send_files_path %></p>
<% if @user.files.attached? %>
  <% @files.each do |file| %>
    <%= link_to(file.blob.filename, file) %>
  <% end %>
<% end %>
<% unless @user.organization? %>
  <p><%= link_to "Открыть бизнес", create_business_path %></p>
  <p><%= link_to "Стать предпринимателем", become_entrepreneur_path %></p>
<% end %>
<p><%= link_to "Информация об имуществе", property_path %></p>

app/views/personal_actions/become_entrepreneur.html.erb
<% if @user.ipid == nil %>
  <h1>Стать предпринимателем</h1>

  <%= form_with(url: "/confirm_status", method: :patch, local: true) do |form| %>
    <div>
      <%= form.submit "Получить идентификатор", class: "btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <h2>Вы уже зарегистрированы как индивидуальный предприниматель.</h2>
  <h2>Ваш ОГРНИП: <%= @user.ipid %></h2>
<% end %>

app/views/personal_actions/create_business.html.erb
<%= link_to "Открыть бизнес", signup_path('organization') %>

app/views/personal_actions/fill_balance.html.erb
<h1>Пополнить баланс</h1>

<p>Текущий баланс: <%= @user.balance %> руб.</p>

<%= form_with(url: update_balance_path, method: :patch, local: true) do |form| %>
  <div>
    <%= form.label :balance, "Сумма пополнения" %>
    <%= form.text_field :balance, class: "form-control" %>

    <%= form.submit "Пополнить", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/personal_actions/pay_taxes.html.erb
<div id="ownerships">
  <%= render partial: 'ownerships' %>
</div>

app/views/personal_actions/property.html.erb
<% unless @current_vehicles.empty? %>
  <% @current_vehicles.each do |vehicle| %>
    <%= link_to vehicle.state_number, vehicle_path(vehicle.id) %>
    <%= vehicle.model %>
    <%= vehicle.vin %>  
  <% end %>
<% end %>

<% unless @current_estates.empty? %>
  <% @current_estates.each do |estate| %>
    <%= link_to estate.cadastaral_number, estate_path(estate.id) %>
    <%= estate.address %>
    <%= estate.square %>  
  <% end %>
<% end %>

<% unless @vehicles.empty? %>
  <% @vehicles.each do |vehicle| %>
    <%= link_to vehicle.state_number, vehicle_path(vehicle.id) %>
    <%= vehicle.model %>
    <%= vehicle.vin %>  
  <% end %>
<% end %>

<% unless @estates.empty? %>
  <% @estates.each do |estate| %>
    <%= link_to estate.cadastaral_number, estate_path(estate.id) %>
    <%= estate.address %>
    <%= estate.square %>  
  <% end %>
<% end %>

app/views/personal_actions/send_files.html.erb
<%= form_with(url: attach_files_path, method: :post, local: true) do |form| %>
  
  <div>
    <%= form.label :files, "Загрузить файлы", style: "display: block" %>
    <%= form.file_field :files, multiple: true %>
  </div>

  <div>
    <%= form.submit "Отправить", class: "btn btn-primary" %>
  </div>
<% end %>